sudo: required
services:
  - docker

before_install:
  - docker build -t dan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dan/react-test npm test


after_success:
  - docker build -t dan/multi-client ./client
  - docker build -t dan/multi-nginx ./nginx
  - docker build -t dan/multi-server ./server
  - docker build -t dan/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dan/multi-client
  - docker push dan/multi-nginx
  - docker push dan/multi-server
  - docker push dan/multi-worker
